// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';
import {prefab} from '../models';

export function DeletePrefab(arg1:string):Promise<pipeline.State>;

export function GenerateMission():Promise<pipeline.State>;

export function GeneratePrefab(arg1:string):Promise<prefab.Prefab>;

export function GetState():Promise<pipeline.State>;

export function LoadProject(arg1:string):Promise<pipeline.State>;

export function MergePlan():Promise<pipeline.State>;

export function NewProject():Promise<pipeline.State>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenIL2Editor():Promise<void>;

export function OpenOutputFolder():Promise<void>;

export function OpenPrefabFolder():Promise<void>;

export function PickFile(arg1:string):Promise<string>;

export function PlacePrefab(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string):Promise<pipeline.State>;

export function QuickMission(arg1:string):Promise<pipeline.State>;

export function SavePrefab(arg1:string):Promise<pipeline.State>;

export function SaveProject(arg1:string):Promise<string>;

export function SetGame(arg1:string):Promise<void>;

export function SetPlanJSON(arg1:string):Promise<pipeline.State>;

export function SetRoleInput(arg1:string,arg2:string):Promise<void>;
