// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';
import {prefab} from '../models';
import {missionfile} from '../models';
import {plan} from '../models';

export function ChallengeMission(arg1:string,arg2:string):Promise<pipeline.State>;

export function DeletePrefab(arg1:string):Promise<pipeline.State>;

export function GenerateMission():Promise<pipeline.State>;

export function GeneratePrefab(arg1:string):Promise<prefab.Prefab>;

export function GetState():Promise<pipeline.State>;

export function LoadProject(arg1:string):Promise<pipeline.State>;

export function MergePlan():Promise<pipeline.State>;

export function MissionAddBriefingText(arg1:string,arg2:string):Promise<missionfile.Doc>;

export function MissionAddKneeboards(arg1:Array<string>):Promise<missionfile.Doc>;

export function MissionClose():Promise<void>;

export function MissionDoc():Promise<missionfile.Doc>;

export function MissionRead(arg1:string):Promise<string>;

export function MissionRemove(arg1:string):Promise<missionfile.Doc>;

export function MissionSave(arg1:string):Promise<missionfile.Doc>;

export function MissionSetBriefingImage(arg1:string):Promise<missionfile.Doc>;

export function MissionSetMeta(arg1:missionfile.Meta):Promise<missionfile.Doc>;

export function MissionWrite(arg1:string,arg2:string):Promise<missionfile.Doc>;

export function NewProject():Promise<pipeline.State>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenGeneratedMission():Promise<missionfile.Doc>;

export function OpenIL2Editor():Promise<void>;

export function OpenMission(arg1:string):Promise<missionfile.Doc>;

export function OpenMissionFolder():Promise<void>;

export function OpenOutputFolder():Promise<void>;

export function OpenPrefabFolder():Promise<void>;

export function PickFile(arg1:string):Promise<string>;

export function PickImage(arg1:string):Promise<string>;

export function PickImages(arg1:string):Promise<Array<string>>;

export function PickMissionFile():Promise<string>;

export function PickMissionSavePath():Promise<string>;

export function PlacePrefab(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string):Promise<pipeline.State>;

export function QuickMission(arg1:string):Promise<pipeline.State>;

export function SavePrefab(arg1:string):Promise<pipeline.State>;

export function SaveProject(arg1:string):Promise<string>;

export function SetGame(arg1:string):Promise<void>;

export function SetMedia(arg1:plan.Media):Promise<pipeline.State>;

export function SetPlanJSON(arg1:string):Promise<pipeline.State>;

export function SetRoleInput(arg1:string,arg2:string):Promise<void>;
