// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChallengeMission(arg1, arg2) {
  return window['go']['main']['App']['ChallengeMission'](arg1, arg2);
}

export function DeletePrefab(arg1) {
  return window['go']['main']['App']['DeletePrefab'](arg1);
}

export function GenerateMission() {
  return window['go']['main']['App']['GenerateMission']();
}

export function GeneratePrefab(arg1) {
  return window['go']['main']['App']['GeneratePrefab'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function MergePlan() {
  return window['go']['main']['App']['MergePlan']();
}

export function MissionAddBriefingText(arg1, arg2) {
  return window['go']['main']['App']['MissionAddBriefingText'](arg1, arg2);
}

export function MissionAddKneeboards(arg1) {
  return window['go']['main']['App']['MissionAddKneeboards'](arg1);
}

export function MissionClose() {
  return window['go']['main']['App']['MissionClose']();
}

export function MissionDoc() {
  return window['go']['main']['App']['MissionDoc']();
}

export function MissionRead(arg1) {
  return window['go']['main']['App']['MissionRead'](arg1);
}

export function MissionRemove(arg1) {
  return window['go']['main']['App']['MissionRemove'](arg1);
}

export function MissionSave(arg1) {
  return window['go']['main']['App']['MissionSave'](arg1);
}

export function MissionSetBriefingImage(arg1) {
  return window['go']['main']['App']['MissionSetBriefingImage'](arg1);
}

export function MissionSetMeta(arg1) {
  return window['go']['main']['App']['MissionSetMeta'](arg1);
}

export function MissionWrite(arg1, arg2) {
  return window['go']['main']['App']['MissionWrite'](arg1, arg2);
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenGeneratedMission() {
  return window['go']['main']['App']['OpenGeneratedMission']();
}

export function OpenIL2Editor() {
  return window['go']['main']['App']['OpenIL2Editor']();
}

export function OpenMission(arg1) {
  return window['go']['main']['App']['OpenMission'](arg1);
}

export function OpenMissionFolder() {
  return window['go']['main']['App']['OpenMissionFolder']();
}

export function OpenOutputFolder() {
  return window['go']['main']['App']['OpenOutputFolder']();
}

export function OpenPrefabFolder() {
  return window['go']['main']['App']['OpenPrefabFolder']();
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function PickImage(arg1) {
  return window['go']['main']['App']['PickImage'](arg1);
}

export function PickImages(arg1) {
  return window['go']['main']['App']['PickImages'](arg1);
}

export function PickMissionFile() {
  return window['go']['main']['App']['PickMissionFile']();
}

export function PickMissionSavePath() {
  return window['go']['main']['App']['PickMissionSavePath']();
}

export function PlacePrefab(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PlacePrefab'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function QuickMission(arg1) {
  return window['go']['main']['App']['QuickMission'](arg1);
}

export function SavePrefab(arg1) {
  return window['go']['main']['App']['SavePrefab'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SetGame(arg1) {
  return window['go']['main']['App']['SetGame'](arg1);
}

export function SetMedia(arg1) {
  return window['go']['main']['App']['SetMedia'](arg1);
}

export function SetPlanJSON(arg1) {
  return window['go']['main']['App']['SetPlanJSON'](arg1);
}

export function SetRoleInput(arg1, arg2) {
  return window['go']['main']['App']['SetRoleInput'](arg1, arg2);
}
